name: Docker Deploy CI

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest      
    steps:
      - uses: actions/checkout@v3
      - name: Build Image
        run: docker build -t solog/solo:latest ./
      - name: Login to registry
        run: docker login --username=${{ secrets.DOCKER_USERNAME }} --password ${{ secrets.DOCKER_PASSWORD }} registry.cn-hangzhou.aliyuncs.com
      - name: Push Image
        run: docker push solog/solo:latest
  pull-docker:
    needs: [build]
    name: Pull Docker
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.HOST_USERNAME }}
          password: ${{ secrets.HOST_PASSWORD }}
          port: ${{ secrets.HOST_PORT }}
          script: |
            docker stop $(docker ps --filter ancestor=${{ secrets.DOCKER_PUBLIC_REPOSITORY }} -q)
            docker rm -f $(docker ps -a --filter ancestor=solog/solo:latest -q)
            docker rmi -f $(docker images solog/solo:latest -q)
            docker login --username=${{ secrets.DOCKER_USERNAME }} --password ${{ secrets.DOCKER_PASSWORD }} registry.cn-hangzhou.aliyuncs.com
            docker pull solog/solo:latest
            docker run -d docker run -d -p 50109:8080 --name solo -v solo-skins:/opt/solo/skins/ --env RUNTIME_DB="MYSQL" --env JDBC_USERNAME="${{ secrets.INNER_BRIGE_MYSQL_USERNAME }}" --env JDBC_PASSWORD="${{ secrets.INNER_BRIGE_MYSQL_PASSWORD }}" --env JDBC_DRIVER="com.mysql.cj.jdbc.Driver" --env JDBC_URL="jdbc:mysql://${{ secrets.INNER_BRIGE_HOST }}:${{ secrets.INNER_BRIGE_MYSQL_PORT }}/solo?useUnicode=yes&characterEncoding=UTF-8&useSSL=false&serverTimezone=UTC" solog/solo:latest --listen_port=8080 --server_scheme=http --server_host=solog.showlife.fun --server_port=8080
